---

- name: Grab info for network switches
  connection: ansible.netcommon.network_cli
  gather_facts: false
  hosts: all
  become: true
  vars_prompt:
    - name: enpassword
      prompt: What is en passoword?
      private: true
    - name: location_name
      prompt: What is the name of the Location?
      private: false
  vars:
    ansible_become_password: "{{enpassword}}"
    location: "{{ location_name }}"
    ansible_network_os: cisco.ios.ios
    dest_vlan: "None"
    device_tracking: "Not Device Tracking capable"
    Rspan_capable: "Not RSPAN capable"
    snmp_location1: "No SNMP Location"
    flash_output1: "No Flash Info"

  tasks:
    - name: Get config for Ios devices
      cisco.ios.ios_facts:
        gather_subset: all
    
    - name: Show monitor sessions
      cisco.ios.ios_command:
        commands: show monitor session all
      register: monitor_output
      ignore_errors: true

    - name: Display a custom message
      ansible.builtin.debug:
        msg: "{{monitor_output}}"
      ignore_errors: true
    
    - name: Find Destination Vlan
      set_fact:
        dest_vlan: "{{ item | regex_search('\\d+') }}"
      loop: "{{ monitor_output.stdout_lines[0]}}"
      when: "'VLAN' in item"
      ignore_errors: true
        
    - name: save show vlan output
      cisco.ios.ios_command:
        commands: show vlan
      register: vlan_output

    - name: save Vlans onThe Switch
      cisco.ios.ios_vlans:
        running_config: "{{ vlan_output.stdout[0] }}"
        state: parsed
      register: vlan_output

    - name: set array of vlans
      set_fact:
        vlan_list: "{{ vlan_output.parsed | map(attribute='vlan_id') | list }}"
      register: vlan_List

    - name: Get_device_tracking_inf_cisco
      cisco.ios.ios_command:
        commands:
          show device-tracking policies 
      register: command_result_cisco
      ignore_errors: true

    - name: if comand result cisco
      ansible.builtin.set_fact:
        device_tracking: "{{ 'device-tracking' if command_result_cisco.stdout_lines[0] | length > 1 else 'no device-tracking'}}"
      ignore_errors: true

    - name: Get_device_tracking_for_stratix
      cisco.ios.ios_command:
        commands:
          sh ip device tracking all
      register: command_result_stratix
      ignore_errors: true

    - name: Get_location
      cisco.ios.ios_command:
        commands:
          show snmp location
      register: snmp_location
      ignore_errors: true

    - name: check if snmp location is configured
      ansible.builtin.set_fact:
        snmp_location1: "{{ snmp_location.stdout_lines[0][0] if snmp_location.stdout_lines[0] | length > 0 else 'No SNMP Location'}}"
      ignore_errors: true

    - name: if comand result stratix
      ansible.builtin.set_fact:
        device_tracking: "{{ 'device-tracking' if command_result_stratix.stdout_lines[0] | length > 4 else 'no device-tracking'}}"
      ignore_errors: true

    - name: display device tracking output
      ansible.builtin.debug:
        msg: "{{ command_result }}"
      ignore_errors: true

    - name: Show monitor session remote vlan
      cisco.ios.ios_command:
        commands: show monitor session remote
      register: rspan_output
      ignore_errors: true
    
    - name: Is id RSPAN Capable
      ansible.builtin.set_fact:
        Rspan_capable: "RSPAN Capable"
      when: rspan_output is not failed
      ignore_errors: true

    - name: Get sync status of SDflash
      cisco.ios.ios_command:
        commands: sh sync status
      register: flash_output
      tags: flash
      ignore_errors: true

    - name: See if flash output is empty
      ansible.builtin.set_fact:
        flash_output1: "{{ flash_output.stdout_lines[0] if flash_output.stdout_lines[0] | length > 1 else 'No Flash Info'}}"
      ignore_errors: true

    - name: Add all variables to a list
      ansible.builtin.set_fact:
        gathered_info:
          - "{{ ansible_net_all_ipv4_addresses | replace(',','-') }}"
          - "{{ ansible_net_hostname | replace(',','-') }}"
          - "{{ ansible_net_model | replace(',','-') }}"
          - "{{ ansible_net_version | replace(',','-') }}"
          - "{{ ansible_net_stacked_serialnums | replace(',','-') }}"
          - "{{ vlan_list | replace(',','-') }}"
          - "{{ dest_vlan | replace(',','-') }}"
          - "{{ device_tracking | replace(',','-') }}"
          - "{{ Rspan_capable | replace(',','-') }}"
          - "{{ snmp_location1 | replace(',','-') }}"
          - "{{ flash_output1 | replace(',','-') }}"
    
#    - name: Ensure CSV header exists
#      ansible.builtin.lineinfile:
#        path: "./{{ location }}/List_sum.csv" 
#        line: "IP Addresses,Hostname,Model,iOS Version,Stacked Serials,Vlan List,Destination VLAN,Device Tracking,RSPAN Capable,SNMP Location,Flash Status"
#        create: yes
#      run_once: true
#      throttle: 1
    - name: Remove a specific file safely
      ansible.builtin.file:
        path: "{{ location }}/List_sum.csv"
        state: absent
      run_once: true
      throttle: 1
      ignore_errors: true

    - name: Save the Config
      ansible.builtin.lineinfile:
        path: "{{ location }}/List_sum.csv" 
        line: "{{ gathered_info[0] }},{{ gathered_info[1] }},{{ gathered_info[2] }},{{ gathered_info[3] }},{{ gathered_info[4] }},{{ gathered_info[5] }},{{ gathered_info[6] }},{{ gathered_info[7] }},{{ gathered_info[8] }},{{ gathered_info[9] }},{{ gathered_info[10] }}"
        create: yes
      throttle: 1
        
    
    - name: Save all to file
      copy:
        content: "{{ ansible_net_config }}"
        dest: "./{{ location }}/{{ ansible_net_hostname }}_sh_run.ios" 
      throttle: 1
# /mnt/c/Users/theronj/Users/theronj/OneDrive - Weyerhaeuser/TheronJ/Documents/Projects/Switch_refresh_PowerBI
# /mnt/c/Users/theronj/OneDrive - Weyerhaeuser/TheronJ/Documents/Projects/Switch_refresh_PowerBI
